# -*- coding: utf-8 -*-
"""Una menos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZ4g77lBH4FzfS2KedI7-YqT42GIbFA9
"""

#18310200 Diana Montoya González 6E1
from random import randrange, choice
import random
from IPython.display import clear_output

#..........Menú principal..........
estancia = 0
while estancia == 0:
  eleccion = 3
  while eleccion != "1" and eleccion != "2":
    print("Bienvenido al juego 'Una menos'")
    eleccion = input("\n Seleccione una opción: \n 1.- Iniciar partida \n 2.-Salir del juego\n\n Escribe solo el número: ")
    if eleccion != "1" and eleccion != "2":
      print("\n ¡ Caracter invalido ! \n")
  if eleccion == "2":
    clear_output()
    print("Chao :)")
    break
  #Inicializa los datos
  elif eleccion == "1":
    participantes = ["Amy", "Emma", "Elia", "Marian", "Sara"]
    personas_por_interrogar = ["Amy", "Emma", "Elia", "Marian", "Sara"]
    objetos = ["un bate, al parecer a alguien le gusta el béisbol", "un cuchillo, deberían guardarlo en su lugar", "una botella vacía, debería de estar en la basura", "una navaja, se ve en buen estado", "un trofeo, debe significar mucho para alguien"]
    causa = ["un bate de béisbol, está muy desgastado y pareciera que está a punto de romperse", "un cuchillo, alguien lo usó recientemente pues es evidente por las manchas que tiene", "una botella, está rota por lo que hay que tener cuidado con las evidencias", "una navaja, su estado es alarmante, no está en buenas condiciones", "un trofeo, fue un gran logro para alguien pero no tuvieron cuidado con él, está roto de la base"]
    causa3 = ["bate", "cuchillo", "botella", "navaja", "trofeo"]
    puestos = ["habitación 1", "habitación 2", "habitación 3", "cocina", "baño"]
    lugares_por_inspeccionar = ["habitación 1", "habitación 2", "habitación 3", "cocina", "baño"]
    habi = ["habitación 1", "habitación 2", "habitación 3"]
    dos_lug = ["cocina", "baño"]
    escena_crimen = []
    mostrar_datos_s = []
    random.shuffle(participantes)
    conclu = 0
    inocentes = ["Amy", "Emma", "Elia", "Marian", "Sara"]
    culpable = (choice(inocentes))
    inocentes.remove(culpable)
    random.shuffle(inocentes)
    ale = [0,1,2,3,4]
    causa2 = []
    arma = []
    random.shuffle(ale)
    causa2.append(causa[ale[0]])
    arma.append(causa3[ale[0]])
    objetos.remove(objetos[ale[0]])
    evid = causa2 + objetos
    random.shuffle(evid)
    sd = 2
    estuvieron_juntas= []
    per = 0
    cocina_o_baño = 0
    restante = []
    ino_evi = []
    evi = []
    #clear_output()
#..........Contexto..........
  print("\nUna menos \n 6 roomies se encontraban en su departamento, cuando los vecinos alarmados al escuchar los gritos de una persona, llaman a la policía. \
  \n En dicho departamento se encontró a Julia sin vida en la puerta principal. Se sabe por las cámaras que nadie sospechoso rondaba cerca antes del crimen, \
  \n además de que nadie salió hasta el momento en que la policía llega al lugar.\
  \n Se tiene como sospechoso a las demás habitantes de ese departamento y se sabe que una de ellas fue la asesina.\
  \n Fuiste llamado para resolver el caso, con algunas pistas y declaraciones de las sospechosas deberás de descubrir de forma acertada al responsable del crimen,\
  \n el arma utilizada y el lugar donde sucedieron los hechos. Si las tres conclusiones son correctas, ganarás el juego y el caso será cerrado.  \n")
  print("Podrás interrogar a las sospechosas, es muy importante que el caso se resuelva rápido por lo que sólo podrás inspeccioanar tres locaciones para \
  \ncomprobar las historias, debes estar atento pues pueden no hablar con la verdad. Mucha suerte...\n")
  
#..........Interrogar sospechosos..........
  seleccionar_frase1 = [0, 1]
  seleccionar_frase2 = [0, 1]
  seleccionar_frase3 = [0, 1]
  if participantes[0] != culpable:
    estuvieron_juntas.append(participantes[0])
  if participantes[2] != culpable:
    estuvieron_juntas.append(participantes[2])
  if participantes[4] != culpable:
    estuvieron_juntas.append(participantes[4])
  while len(personas_por_interrogar) != 0:
    print("\nEscribe el nombre de la persona a interrogar: ")
    contador1 = 0

    #Ciclo para nombrar a los sospechosos
    while contador1 < len(personas_por_interrogar):
      print(personas_por_interrogar[contador1])
      contador1 = contador1 + 1
    persona = input("\n")
    #Interrogatorio
    if (persona in personas_por_interrogar) == True:
      historia_de = participantes.index(persona)
      
      if historia_de == 0:  
        m = 1
        if estuvieron_juntas[m] == persona:
          m = m - 1
        if len(ino_evi) == 0:
          random.shuffle(habi)
          ino_evi.append(habi[0])
          habi.remove(ino_evi[0])
        if len(evi) == 0:
          random.shuffle(habi)
          evi.append(habi[0])
          habi.remove(evi[0])
        if participantes[historia_de] != (culpable):
          if sd > 0:
            if per == 0:
              print(persona,": Yo soy inocente, si me pregunta que pasó le diré que no tengo ni la menor idea, estaba dormida cuando un fuerte grito me despertó, \n me encontraba con \n ", estuvieron_juntas[m], "en la habitación")
              per = 1
              restante.append(persona)
            else:
              print(persona,": Yo soy inocente, si me pregunta que pasó le diré que no tengo ni la menor idea, estaba dormida\n cuando un fuerte grito me despertó, \n me encontraba con \n ", restante[0], "en la habitación")
            sd = sd - 1
          else:
            print(persona,": Yo soy inocente, si me pregunta que pasó le diré que no tengo ni la menor idea, estaba dormida\n cuando un fuerte grito me despertó")
        else:
          random.shuffle(habi)
          escena_crimen.append(choice(habi))
          habi.remove(escena_crimen[0])
          #random.shuffle(estuvieron_juntas)
          print(persona,": Yo soy inocente, si me pregunta que pasó \n le diré que no tengo ni la menor idea, estaba dormida\n cuando un fuerte grito me despertó")  #, me encontraba con \n ", estuvieron_juntas[m], "en la habitación")
      if historia_de == 1:  
        random.shuffle(dos_lug)
        if dos_lug[1] == "cocina":
          cocina_o_baño = 1
          if participantes[historia_de] != (culpable):
            print(persona,": Cada día hay más personas locas en este mundo, como dice el dicho: 'caras vemos, corazones no sabemos'. Como sea, yo estaba en la cocina \n preparándome un sandwich")
          else:
            print(persona,": Cada día hay más personas locas en este mundo, como dice el dicho: 'caras vemos, corazones no sabemos'. Como sea, yo estaba en la cocina \n preparándome un sandwich")
            escena_crimen = ["cocina"]
        if dos_lug[1] == "baño":
          cocina_o_baño = 2
          if participantes[historia_de] != (culpable):
            print(persona,": No pude haber sido yo, estaba tomando un baño y me asusté al escuchar tanto ruido.")
          else:
            print(persona,": No pude haber sido yo, estaba tomando un baño y me asusté al escuchar tanto ruido.")
            escena_crimen = ["baño"]
      if historia_de == 2:  
        n = 3
        if inocentes[n] == persona:
          n = n-1
        m = 1
        if estuvieron_juntas[m] == persona:
          m = m - 1  
        if len(ino_evi) == 0:
          random.shuffle(habi)
          ino_evi.append(habi[0])
          habi.remove(ino_evi[0])
        if len(evi) == 0:
          random.shuffle(habi)
          evi.append(habi[0])
          habi.remove(evi[0])
        if participantes[historia_de] != (culpable):
          if sd > 0:
            if per == 0:
              print(persona,": Fue ", culpable, "la vi muy agitada cuando descubrimos a Julia. Yo estaba con ", estuvieron_juntas[m], " en la ", ino_evi[0])
              per = 1
              restante.append(persona)
            else:
              print(persona,": Fue ", culpable, "la vi muy agitada cuando descubrimos a Julia. Yo estaba con ", restante[0], " en la ", ino_evi[0])
            sd = sd - 1
          else:
            print(persona,": Fue ", culpable, "la vi muy agitada cuando descubrimos a Julia. Yo estaba en la ", evi[0])
        else:
          random.shuffle(estuvieron_juntas)
          print(persona,": Fue ", inocentes[n], "la vi muy agitada cuando descubrimos a Julia. Yo estaba con ", estuvieron_juntas[m])
          random.shuffle(habi)
          escena_crimen.append(choice(habi))
          habi.remove(escena_crimen[0])
      if historia_de == 3:  
        n = 4
        if participantes[n] == persona:
          n = n-1
        if participantes[historia_de] != (culpable):
          print(persona,": Sigo desconcertada, no sé como esto pudo pasar. Creo haber visto a ", participantes[n], ",\n la verdad siempre me dió mala espina") #Estaba en el baño
        else:
          random.shuffle(habi)
          escena_crimen.append(choice(habi))
          habi.remove(escena_crimen[0])
          print(persona,": Sigo desconcertada, no sé como esto pudo pasar. Creo haber visto a ", participantes[n], ",\n la verdad siempre me dió mala espina")
      if historia_de == 4:  
        m = 0
        if estuvieron_juntas[m] == persona:
          m = m + 1
        if len(ino_evi) == 0:
          random.shuffle(habi)
          ino_evi.append(habi[0])
          habi.remove(ino_evi[0])
        if len(evi) == 0:
          random.shuffle(habi)
          evi.append(habi[0])
          habi.remove(evi[0])
        if participantes[historia_de] != (culpable):
          if sd > 0:
            if per == 0:
              print(persona,": No tienen que desconfiar de mi, yo no sería capaz de hacer algo como eso. Yo estaba con ", estuvieron_juntas[m], " en la ", ino_evi[0])
              per = 1
              restante.append(persona)
            else:
              print(persona,": No tienen que desconfiar de mi, yo no sería capaz de hacer algo como eso. Yo estaba con ", restante[0], " en la ", ino_evi[0])
            sd = sd - 1
          else:
            print(persona,": No tienen que desconfiar de mi, yo no sería capaz de hacer algo como eso. Yo estaba en la ", evi[0])
        else:
          random.shuffle(estuvieron_juntas)
          print(persona,": No tienen que desconfiar de mi, yo no sería capaz de hacer algo como eso.\n Yo estaba con ", estuvieron_juntas[m])
          random.shuffle(habi)
          escena_crimen.append(choice(habi))
          habi.remove(escena_crimen[0])

      personas_por_interrogar.remove(persona)
    else:
      print("\nOpción inválida\n")
#..........Inspeccionar lugares..........
  lugares=0
  while lugares < 3:
    contador2 = 0
    print("\n Escribe el lugar por inspeccionar: ")
    while contador2 < len(lugares_por_inspeccionar):
      print(lugares_por_inspeccionar[contador2])
      contador2 = contador2 + 1
    print("Si ya tienes tus conclusiones escribe 'siguiente'")
    lugar = input("\n")
    if (lugar in lugares_por_inspeccionar) == True:
      lugares_por_inspeccionar.remove(lugar)
      #clear_output()
      lugares = lugares + 1
      if lugar == 'habitación 1' or lugar == 'habitación 2' or lugar == 'habitación 3':
        random.shuffle(seleccionar_frase1)
        #random.shuffle(seleccionar_frase2)
        if lugar == escena_crimen[0]:
          if seleccionar_frase1[0] == 0:
            print("La ", lugar, " está hecho un completo desastre. Dicen las sospechosas que el lugar sule estar un poco desordenado pero esta vez todo se encuentra \n en el suelo e incluso se encuentran algunos muebles fuera del lugar, debajo de la cama hay rastros de sangre. Se encontró en la cama \n", evid[0])
            seleccionar_frase1.remove(0)
            evid.remove(evid[0])
          else:
            print("La ", lugar, " tiene una gran mancha de sangre en la alfombra y las paredes se encuentan salpicadas. En una repisa se encuentra \n", evid[0])
            seleccionar_frase1.remove(1)
            evid.remove(evid[0])
        else:
          #if seleccionar_frase2[0] == 0:
          if lugar == ino_evi[0]:
            print("En la ", lugar, "se ve todo normal, lo más notorio es una cama destendida, una mochila en el suelo y \n", evid[0])
            evid.remove(evid[0])
            #seleccionar_frase2.remove(0)
          #elif seleccionar_frase2[0] == 1:
          elif lugar == evi[0]:
            print("La ", lugar, "está desordenada y huele extraño, confirman las sospechosas que así sule estar siempre. En la entrada se encontró \n", evid[0])
            evid.remove(evid[0])
            #seleccionar_frase2.remove(1)
          else:
            print("La ", lugar, "está más limpia que nunca, es un lugar ordenado y pareciera que nadie estuvo ahí antes del crímen. Sólo un detalle, el la alfombra está \n", evid[0], ".")
            evid.remove(evid[0])
            #seleccionar_frase2.remove(2)
      if lugar == 'cocina':
        random.shuffle(seleccionar_frase2)
        random.shuffle(seleccionar_frase3)
        if lugar == escena_crimen[0]:
          if seleccionar_frase2[0] == 0:
            print("Pareciera que nadie ha cocinado algo en todo el día, todo está en su lugar pero hay evidentes manchas de sangre por todo el piso, En la estufa se encuentra \n", evid[0])
            seleccionar_frase2.remove(0)
            evid.remove(evid[0])
          elif seleccionar_frase2[0] == 1:
            print("Los cajones se encuentran abiertos y un poco revueltos, es alarmante las manchas que se encontraron, en el suelo hay \n", evid[0])
            seleccionar_frase2.remove(1)
            evid.remove(evid[0])
        else:
          if cocina_o_baño == 2:
            if seleccionar_frase3[0] == 0:
              print("Los cajones se encuentran abiertos y un poco revueltos, en la mesa hay ", evid[0])
              seleccionar_frase3.remove(0)
              evid.remove(evid[0])
            elif seleccionar_frase3[0] == 1:
              print("Pareciera que nadie ha cocinado algo en todo el día, todo está en su lugar, salvo que hay en el suelo \n", evid[0], ".")
              seleccionar_frase3.remove(1)
              evid.remove(evid[0])
          else:
            print("Lo más notorio de la cocina es que se encuentran unos vegetales y una barra de pan en la mesa, además de que se encontraba en la estufa \n", evid[0], ", de ahí en más todo se ve bien")
            evid.remove(evid[0])
      if lugar == 'baño':
        if lugar == escena_crimen[0]:
          print("Es evidente ", evid[0], ".El baño está desordenado y aparentemente limpio pero se puede notar en los bordes de la bañera unas pequeñas manchas de sangre, \n ¿alguien tuvo un pequeño accidente durante la ducha o tal vez se trató de limpiar la escena del crimen? hmmm...")
          evid.remove(evid[0])
        else:
          if cocina_o_baño == 1:
            print("El baño se encuentra limpio y ordenado, parece que nadie ha tomado un baño pues la ducha está seca. En la bañera se encuentra \n", evid[0])
            evid.remove(evid[0])
          else:
            print("Parece que alguien se ha dado una ducha, el baño se encuentra mojado y en el suelo hay \n", evid[0], " de ahí en más todo se ve bien.")
            evid.remove(evid[0])
      if (lugar == 'siguiente') or (lugares == 3):
        lugares = 3
        ch1 = 0
        if ch1 == 0:
          mculp = input("Escribe el nombre de la culpable:\n Amy \n Emma \n Elia \n Marian \n Sara \n")
          if (mculp == "Amy") or (mculp == "Emma") or (mculp == "Elia") or (mculp == "Marian") or (mculp == "Sara"):
            ch1 = 1
            if ch1 == 1:
              if mculp == culpable: 
                print("Correcto \n")
                conclu = conclu + 1
              else:
                print("La culpable en realidad fue ", culpable) 
        ch2 = 0
        if ch2 == 0:
          mlug = input("Escribe la escena del crimen:\n habitación 1 \n habitación 2 \n habitación 3 \n baño \n cocina \n")
          if (mlug == "habitación 1") or (mlug == "habitación 2") or (mlug == "habitación 3") or (mlug == "baño") or (mlug == "cocina"):
            ch2 = 1
            if ch2 == 1:
              if mlug == escena_crimen[0]:
                print("Correcto \n")
                conclu = conclu + 1
              else:
                print("El lugar en realidad fue ", escena_crimen[0]) 
        ch3 = 0
        if ch3 == 0:
          marm = input("Escribe el nombre del arma:\n bate \n cuchillo \n botella \n navaja \n trofeo \n")
          if (marm == "bate") or (marm == "cuchillo") or (marm == "botella") or (marm == "navaja") or (marm == "trofeo"):
            ch3 = 1
            if ch3 == 1:
              if marm == arma[0]:
                print("Correcto \n")
                conclu = conclu + 1
              else:
                print("El arma en realidad fue ", arma[0])
        if conclu == 3:
          print("Felicidades, resolviste el caso con éxito\n\n\n\n")
        elif conclu != 3:
          print("Lo lamento, no descubriste el caso de forma correcta\n\n\n\n")
        #clear_output()
        break
    else:
      print("\nOpción inválida\n")
      #clear_output()
  juego_num = 0